# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup cache environment
      run: mkdir -p $(yarn cache dir)
    
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: $(yarn cache dir)
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: yarn setup
      run: npm install -g yarn@latest

    - name: install dependencies
      run: yarn install

    - name: build
      run: yarn build

    - name: lint
      run: yarn lint
